"""empty message

Revision ID: 2264b5c985d4
Revises: 2307977beea8
Create Date: 2018-05-21 15:13:32.612248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2264b5c985d4'
down_revision = '2307977beea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('title', sa.String(length=128), nullable=True))
    op.add_column('faculty', sa.Column('title', sa.String(length=128), nullable=True))
    op.add_column('group', sa.Column('title', sa.String(length=128), nullable=True))
    op.add_column('specialty', sa.Column('title', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specialty', 'title')
    op.drop_column('group', 'title')
    op.drop_column('faculty', 'title')
    op.drop_column('course', 'title')
    # ### end Alembic commands ###
