"""empty message

Revision ID: 2307977beea8
Revises: e4e63f7ed932
Create Date: 2018-05-19 17:49:56.486277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2307977beea8'
down_revision = 'e4e63f7ed932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('number_of_course', sa.Integer(), nullable=True))
    op.drop_column('course', 'name')
    op.add_column('group', sa.Column('number_of_group', sa.String(length=128), nullable=True))
    op.drop_column('group', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=128), nullable=True))
    op.drop_column('group', 'number_of_group')
    op.add_column('course', sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=128), nullable=True))
    op.drop_column('course', 'number_of_course')
    # ### end Alembic commands ###
