"""empty message

Revision ID: 7e11f2826b11
Revises: 
Create Date: 2018-05-28 16:44:52.594734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e11f2826b11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('username', sa.String(length=128), nullable=True))
    op.drop_index('login', table_name='admin')
    op.create_unique_constraint(None, 'admin', ['username'])
    op.drop_column('admin', 'login')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('login', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'admin', type_='unique')
    op.create_index('login', 'admin', ['login'], unique=True)
    op.drop_column('admin', 'username')
    # ### end Alembic commands ###
