"""empty message

Revision ID: 856afe24295b
Revises: 2264b5c985d4
Create Date: 2018-05-21 15:17:13.882776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '856afe24295b'
down_revision = '2264b5c985d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('entity', sa.String(length=128), nullable=True))
    op.drop_column('course', 'title')
    op.add_column('faculty', sa.Column('entity', sa.String(length=128), nullable=True))
    op.drop_column('faculty', 'title')
    op.add_column('group', sa.Column('entity', sa.String(length=128), nullable=True))
    op.drop_column('group', 'title')
    op.add_column('specialty', sa.Column('entity', sa.String(length=128), nullable=True))
    op.drop_column('specialty', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialty', sa.Column('title', mysql.VARCHAR(collation='utf8_unicode_ci', length=128), nullable=True))
    op.drop_column('specialty', 'entity')
    op.add_column('group', sa.Column('title', mysql.VARCHAR(collation='utf8_unicode_ci', length=128), nullable=True))
    op.drop_column('group', 'entity')
    op.add_column('faculty', sa.Column('title', mysql.VARCHAR(collation='utf8_unicode_ci', length=128), nullable=True))
    op.drop_column('faculty', 'entity')
    op.add_column('course', sa.Column('title', mysql.VARCHAR(collation='utf8_unicode_ci', length=128), nullable=True))
    op.drop_column('course', 'entity')
    # ### end Alembic commands ###
